# Databricks notebook source
# MAGIC %md
# MAGIC # Vibe Coding Workshop — Admin Pre-Workshop Setup
# MAGIC
# MAGIC **Audience:** the workshop admin runs this notebook **once** before the workshop. Participants do not run it.
# MAGIC
# MAGIC It does four things:
# MAGIC
# MAGIC 1. Wires up the **shared synthetic dataset** (the same `mvp_quality_workshop` star schema used by the Metric Views workshop) and (re)creates the operational `patients` + `care_gaps` views this app queries.
# MAGIC 2. Opens read access to that dataset for all workshop participants, and grants them `CREATE SCHEMA` on the catalog so they can self-serve their own personal write schemas during the workshop.
# MAGIC 3. Walks you through deploying the shared **Visual Builder App** from the [`ai-dev-kit`](https://github.com/databricks-solutions/ai-dev-kit#visual-builder-app) and granting all participants `CAN_USE` on it.
# MAGIC 4. Grants the Builder App's service principal the permissions it needs to read your data.
# MAGIC
# MAGIC > **Prerequisite:** the shared dataset is generated by the Metric Views workshop's `00_setup_quality_data`
# MAGIC > notebook ([repo](https://github.com/philsalm/mvp-metric-views-workshop)). Run it against your target
# MAGIC > catalog/schema first (or confirm it's already loaded) — Section 1 below verifies it and fails fast if missing.
# MAGIC
# MAGIC Plan ~30 minutes, including the Builder App deploy. You can run Section 1 immediately; Sections 2 and 3 depend on the Builder App being deployed first.
# MAGIC
# MAGIC ---

# COMMAND ----------

# MAGIC %md
# MAGIC ## Configuration
# MAGIC
# MAGIC Set the widgets at the top of the notebook before running any cells.
# MAGIC
# MAGIC | Widget | Description |
# MAGIC |--------|-------------|
# MAGIC | `catalog` | Unity Catalog catalog holding the shared dataset. **Required.** You must have `MANAGE` (or be the owner) to issue the downstream grants. |
# MAGIC | `schema` | Schema holding the shared star schema + views. Default: `mvp_quality_workshop` (matches the Metric Views workshop). |
# MAGIC | `sql_warehouse_name` | Name of the serverless SQL warehouse the Builder App will use. Default: `Serverless Starter Warehouse`. |
# MAGIC | `participants_group` | **Account-level** group that gets read access to the shared data, `CAN_USE` on the Builder App, and `CREATE SCHEMA` on the catalog. Default: `account users` (every user in the Databricks account). **Important:** use the account-level group identifier, not a workspace-level group like `users` — Unity Catalog grants on schemas and tables resolve against account-level principals, and a workspace-only group will fail with `PRINCIPAL_DOES_NOT_EXIST`. |

# COMMAND ----------

dbutils.widgets.text("catalog", "", "Catalog (required)")
dbutils.widgets.text("schema", "mvp_quality_workshop", "Schema")
dbutils.widgets.text("sql_warehouse_name", "Serverless Starter Warehouse", "SQL warehouse name")
dbutils.widgets.text("participants_group", "account users", "Workshop participants group")

CATALOG = dbutils.widgets.get("catalog").strip()
SCHEMA = dbutils.widgets.get("schema").strip()
WAREHOUSE = dbutils.widgets.get("sql_warehouse_name").strip()
PARTICIPANTS_GROUP = dbutils.widgets.get("participants_group").strip() or "account users"

assert CATALOG, "Set the 'catalog' widget before running this notebook."
assert SCHEMA, "Set the 'schema' widget."
assert WAREHOUSE, "Set the 'sql_warehouse_name' widget."

print(f"Shared dataset: {CATALOG}.{SCHEMA}")
print(f"Warehouse:      {WAREHOUSE}")
print(f"Group:          {PARTICIPANTS_GROUP}")

# COMMAND ----------

# MAGIC %md
# MAGIC %md
# MAGIC ## Section 1 — Wire up the shared synthetic dataset
# MAGIC
# MAGIC This workshop runs on the **same governed dataset** as the *Unity Catalog Metric Views* workshop —
# MAGIC one source of truth feeding both a metric view (analytics) and this Care Gap Outreach app (operations).
# MAGIC
# MAGIC This section does **not** generate data. It:
# MAGIC
# MAGIC 1. Verifies the shared star schema exists in `{catalog}.{schema}` (default schema `mvp_quality_workshop`).
# MAGIC 2. (Re)creates the operational `patients` and `care_gaps` views the app queries.
# MAGIC 3. Opens read access to participants and grants them `CREATE SCHEMA` for personal write schemas.
# MAGIC 4. Opens the SQL warehouse for their apps' OBO queries.
# MAGIC
# MAGIC > **Prerequisite:** run the metric-views workshop's `00_setup_quality_data` notebook first — it generates
# MAGIC > the star schema (and these views). Repo: https://github.com/philsalm/mvp-metric-views-workshop
# MAGIC > If you've already run it against this catalog/schema, you're set; this section is idempotent.

# COMMAND ----------

# MAGIC %md
# MAGIC ### 1a — Verify the shared dataset exists

# COMMAND ----------

REQUIRED_TABLES = ["dim_member", "dim_provider", "dim_plan", "dim_measure", "fact_measure_compliance"]
existing = {r["tableName"] for r in spark.sql(f"SHOW TABLES IN {CATALOG}.{SCHEMA}").collect()}
missing = [t for t in REQUIRED_TABLES if t not in existing]
assert not missing, (
    f"Missing base tables in {CATALOG}.{SCHEMA}: {missing}.\n"
    f"Run the metric-views workshop's 00_setup_quality_data notebook against this catalog/schema first:\n"
    f"  https://github.com/philsalm/mvp-metric-views-workshop"
)
print(f"Shared dataset found in {CATALOG}.{SCHEMA}: {sorted(REQUIRED_TABLES)}")

# COMMAND ----------

# MAGIC %md
# MAGIC ### 1b — Create the operational views the app queries
# MAGIC
# MAGIC The metric-views setup already creates these; we (re)create them here so this workshop is self-sufficient
# MAGIC and the views are guaranteed present. `patients` reshapes `dim_member` (+ plan + PCP) keyed by `mrn`;
# MAGIC `care_gaps` is the open (non-compliant) current-year rows with due date + priority.

# COMMAND ----------

spark.sql(f"""
CREATE OR REPLACE VIEW {CATALOG}.{SCHEMA}.patients AS
SELECT
  m.member_id        AS mrn,
  m.first_name, m.last_name, m.age,
  m.gender           AS sex,
  prov.provider_name AS primary_pcp,
  pln.plan_name      AS insurance_plan,
  m.preferred_contact, m.phone, m.email, m.last_visit_date
FROM {CATALOG}.{SCHEMA}.dim_member m
LEFT JOIN {CATALOG}.{SCHEMA}.dim_provider prov ON m.pcp_provider_id = prov.provider_id
LEFT JOIN {CATALOG}.{SCHEMA}.dim_plan     pln  ON m.plan_id         = pln.plan_id
""")

spark.sql(f"""
CREATE OR REPLACE VIEW {CATALOG}.{SCHEMA}.care_gaps AS
SELECT
  CONCAT(f.member_id, '-', f.measure_id, '-', f.measurement_year) AS gap_id,
  f.member_id       AS mrn,
  f.measure_id      AS measure,
  meas.measure_name AS measure_description,
  f.due_date, f.last_completed_date, f.priority, f.source
FROM {CATALOG}.{SCHEMA}.fact_measure_compliance f
JOIN {CATALOG}.{SCHEMA}.dim_measure meas ON f.measure_id = meas.measure_id
WHERE f.compliant_flag = 0
  AND f.measurement_year = (SELECT MAX(measurement_year) FROM {CATALOG}.{SCHEMA}.fact_measure_compliance)
""")
print(f"Views {CATALOG}.{SCHEMA}.patients and {CATALOG}.{SCHEMA}.care_gaps ready.")

# COMMAND ----------

# MAGIC %md
# MAGIC ### 1c — Validate
# MAGIC
# MAGIC Open care gaps by measure and priority, and a sample of the joined rows the app will display.

# COMMAND ----------

display(spark.sql(f"""
    SELECT measure, priority, COUNT(*) AS gap_count
    FROM {CATALOG}.{SCHEMA}.care_gaps
    GROUP BY measure, priority
    ORDER BY measure, priority
"""))

# COMMAND ----------

display(spark.sql(f"""
    SELECT p.first_name, p.last_name, p.age, p.sex, p.insurance_plan, p.primary_pcp, p.preferred_contact,
           g.measure, g.priority, g.due_date
    FROM {CATALOG}.{SCHEMA}.care_gaps g
    JOIN {CATALOG}.{SCHEMA}.patients p ON g.mrn = p.mrn
    ORDER BY g.due_date
    LIMIT 15
"""))

# COMMAND ----------

# MAGIC %md
# MAGIC ### 1d — Open access to workshop participants
# MAGIC
# MAGIC Three grants for the participants group (`account users` by default — the account-level system group containing every user in your Databricks account):
# MAGIC
# MAGIC 1. `USE CATALOG` + `USE SCHEMA` + `SELECT ON SCHEMA` so participants (and the apps they build, via on-behalf-of-user auth) can query the shared data. The schema-level `SELECT` cascades to `patients`, `care_gaps`, and the underlying tables.
# MAGIC 2. `CREATE SCHEMA` on the catalog so each participant can self-serve their own personal write schema (e.g., `workshop_<their_username>`) for their app's Module 2 state — keeping participants from overwriting one another.
# MAGIC 3. `CAN_USE` on the SQL warehouse via the workspace permissions API (next cell) so their apps can route OBO queries through it. Warehouse permissions are not managed via SQL `GRANT` — we set them via `/api/2.0/permissions/warehouses/{id}`.

# COMMAND ----------

participant_grants_sql = f"""
-- Read access for participants on the shared dataset (SELECT ON SCHEMA cascades to all tables + views).
GRANT USE CATALOG ON CATALOG `{CATALOG}` TO `{PARTICIPANTS_GROUP}`;
GRANT USE SCHEMA  ON SCHEMA  `{CATALOG}`.`{SCHEMA}` TO `{PARTICIPANTS_GROUP}`;
GRANT SELECT      ON SCHEMA  `{CATALOG}`.`{SCHEMA}` TO `{PARTICIPANTS_GROUP}`;

-- Let each participant create their own personal write schema in the catalog.
GRANT CREATE SCHEMA ON CATALOG `{CATALOG}` TO `{PARTICIPANTS_GROUP}`;
"""

print(participant_grants_sql)

for stmt in [s.strip() for s in participant_grants_sql.strip().split(";") if s.strip() and not s.strip().startswith("--")]:
    try:
        spark.sql(stmt)
        print(f"OK:     {stmt[:90]}")
    except Exception as e:
        print(f"FAILED: {stmt[:90]}")
        print(f"        -> {type(e).__name__}: {str(e)[:160]}")

# COMMAND ----------

# MAGIC %md
# MAGIC Grant `CAN_USE` on the SQL warehouse to the participants group via the permissions API.

# COMMAND ----------

import json
from databricks.sdk import WorkspaceClient

w = WorkspaceClient()

# Look up the warehouse ID from the name
warehouse_id = None
for wh in w.warehouses.list():
    if wh.name == WAREHOUSE:
        warehouse_id = wh.id
        break
assert warehouse_id, f"Warehouse named '{WAREHOUSE}' not found in this workspace"

print(f"Warehouse '{WAREHOUSE}' resolved to id={warehouse_id}")

# Patch the warehouse permissions to add CAN_USE for the participants group
try:
    w.api_client.do(
        method="PATCH",
        path=f"/api/2.0/permissions/warehouses/{warehouse_id}",
        body={
            "access_control_list": [
                {"group_name": PARTICIPANTS_GROUP, "permission_level": "CAN_USE"}
            ]
        },
    )
    print(f"OK: granted CAN_USE on warehouse {warehouse_id} to '{PARTICIPANTS_GROUP}'")
except Exception as e:
    print(f"FAILED to grant warehouse CAN_USE: {type(e).__name__}: {str(e)[:200]}")
    print("If you don't have admin permission on this warehouse, ask a workspace admin to run the equivalent grant in the UI:")
    print(f"  SQL > SQL Warehouses > '{WAREHOUSE}' > Permissions > Add '{PARTICIPANTS_GROUP}' with Can use")

# COMMAND ----------

# MAGIC %md
# MAGIC Section 1 is done — shared data is created and accessible to participants, and the warehouse is opened up for their apps' OBO queries. Continue to Section 2 to deploy the shared Builder App.
# MAGIC
# MAGIC ---

# COMMAND ----------

# MAGIC %md
# MAGIC ## Section 2 — Deploy the shared Visual Builder App
# MAGIC
# MAGIC One Builder App, deployed by you, used by every workshop participant. Run these steps **from your laptop terminal**, not from this notebook — the install is a shell script that needs the Databricks CLI on your local machine.
# MAGIC
# MAGIC ### Prerequisites on your laptop
# MAGIC
# MAGIC | Tool | Check | Install |
# MAGIC |------|-------|---------|
# MAGIC | Databricks CLI v0.287.0+ | `databricks --version` | [docs.databricks.com/dev-tools/cli/install](https://docs.databricks.com/aws/en/dev-tools/cli/install) |
# MAGIC | Node.js 20+ | `node --version` | [nodejs.org](https://nodejs.org) |
# MAGIC | `uv` package manager | `uv --version` | `curl -LsSf https://astral.sh/uv/install.sh \| sh` |
# MAGIC | CLI profile for this workspace | `databricks auth profiles` | `databricks auth login --host <your-workspace-url>` |
# MAGIC
# MAGIC ### Deploy steps
# MAGIC
# MAGIC ```bash
# MAGIC # 1. Clone the ai-dev-kit repo
# MAGIC git clone https://github.com/databricks-solutions/ai-dev-kit.git
# MAGIC cd ai-dev-kit/databricks-builder-app
# MAGIC
# MAGIC # 2. Deploy. Replace <your-cli-profile> with your CLI profile name.
# MAGIC ./scripts/deploy.sh my-builder-app --profile <your-cli-profile>
# MAGIC ```
# MAGIC
# MAGIC The deploy script provisions a Lakebase database, creates the Databricks App, configures Postgres permissions for the app's service principal, builds the React frontend, and starts the app. The first deploy takes ~5–10 minutes.
# MAGIC
# MAGIC When it finishes, it prints the app URL — something like `https://my-builder-app-<workspace-id>.<region>.databricksapps.com`. Open it. You should see the Builder App chat UI.
# MAGIC
# MAGIC ### Add the SQL warehouse as an app resource
# MAGIC
# MAGIC The `deploy.sh` script does not bind a SQL warehouse to the app — you need to do this explicitly. Binding the warehouse as an **app resource** is the right pattern: it auto-grants the app's service principal `CAN_USE` on the warehouse and exposes the warehouse ID to the app's runtime via env vars, so you don't have to hand-grant warehouse permissions separately.
# MAGIC
# MAGIC You can do this two ways:
# MAGIC
# MAGIC **From the CLI** (replace the warehouse ID with your own):
# MAGIC
# MAGIC ```bash
# MAGIC databricks apps add-resource my-builder-app --json '{
# MAGIC   "name": "sql-warehouse",
# MAGIC   "sql_warehouse": {
# MAGIC     "id": "<your-warehouse-id>",
# MAGIC     "permission": "CAN_USE"
# MAGIC   }
# MAGIC }' --profile <your-cli-profile>
# MAGIC ```
# MAGIC
# MAGIC Find your warehouse ID with `databricks warehouses list --profile <your-cli-profile>` (it's the value in the `ID` column for the warehouse you set in the `sql_warehouse_name` widget at the top of this notebook).
# MAGIC
# MAGIC **From the UI:** open **Compute > Apps > `my-builder-app` > Resources > Add resource**, choose **SQL Warehouse**, pick your warehouse, set permission to **Can use**, save. The app will redeploy automatically.
# MAGIC
# MAGIC ### Find the app's service principal
# MAGIC
# MAGIC Databricks Apps auto-provisions a service principal for each app. You'll need its **application ID** (a UUID) to grant Unity Catalog access in Section 3.
# MAGIC
# MAGIC 1. In the workspace UI, open **Compute > Apps**.
# MAGIC 2. Click `my-builder-app`.
# MAGIC 3. On the overview tab, find the row labeled **Service principal** or **Service principal client ID**. The value is a UUID, e.g., `bf7b7f5b-c9d4-4ce2-8f50-7b4725c047a1`.
# MAGIC 4. Copy the UUID and paste it into the `app_sp_client_id` widget at the top of Section 3 below.
# MAGIC
# MAGIC You can also retrieve it from the CLI: `databricks apps get my-builder-app --profile <your-cli-profile>` — look for `service_principal_client_id` in the output.
# MAGIC
# MAGIC ### Grant participants `CAN_USE` on the Builder App
# MAGIC
# MAGIC The deploy creates the app private to you. Open it up to your workshop participants group so they can launch it on the day.
# MAGIC
# MAGIC **From the CLI** (replace the group name to match your `participants_group` widget value):
# MAGIC
# MAGIC ```bash
# MAGIC databricks api patch /api/2.0/permissions/apps/my-builder-app \
# MAGIC   --profile <your-cli-profile> \
# MAGIC   --json '{
# MAGIC     "access_control_list": [
# MAGIC       {"group_name": "account users", "permission_level": "CAN_USE"}
# MAGIC     ]
# MAGIC   }'
# MAGIC ```
# MAGIC
# MAGIC **From the UI:** **Compute > Apps > `my-builder-app` > Permissions > Add**, pick the participants group, set permission to **Can use**, save.
# MAGIC
# MAGIC Participants will reach the app at the URL printed by `deploy.sh` (something like `https://my-builder-app-<workspace-id>.<region>.databricksapps.com`). Send them that URL in your workshop logistics email.
# MAGIC
# MAGIC ---

# COMMAND ----------

# MAGIC %md
# MAGIC ## Section 3 — Grant the Builder App's service principal access to your Unity Catalog data
# MAGIC
# MAGIC One Builder App, one service principal — this is the only SP that needs UC grants. Section 1d already covered direct user access; this section covers the app's own queries (for example, when the Builder App reads schema metadata to help a participant write SQL).
# MAGIC
# MAGIC Set the `app_sp_client_id` widget below to the UUID from Section 2, then run the next cells. The notebook prints the GRANT SQL and attempts to execute it; if you don't have admin privileges, copy the SQL and hand it to a workspace / metastore admin.

# COMMAND ----------

dbutils.widgets.text("app_sp_client_id", "", "Builder App service principal client ID (UUID)")

SP_CLIENT_ID = dbutils.widgets.get("app_sp_client_id").strip()

assert SP_CLIENT_ID, "Set the 'app_sp_client_id' widget to the service principal UUID from Section 2 before running."

grants_sql = f"""
-- Grant the Builder App's service principal read access on the shared dataset.
-- SELECT ON SCHEMA cascades to patients, care_gaps, and the underlying tables.
-- Run as a workspace / metastore admin if any fail below.

GRANT USE CATALOG ON CATALOG `{CATALOG}` TO `{SP_CLIENT_ID}`;
GRANT USE SCHEMA  ON SCHEMA  `{CATALOG}`.`{SCHEMA}` TO `{SP_CLIENT_ID}`;
GRANT SELECT      ON SCHEMA  `{CATALOG}`.`{SCHEMA}` TO `{SP_CLIENT_ID}`;
"""

print(grants_sql)

# COMMAND ----------

# Attempt to run each grant. Any that fail will be printed so you (or an admin) can rerun them.
statements = [s.strip() for s in grants_sql.strip().split(";") if s.strip() and not s.strip().startswith("--")]
for stmt in statements:
    try:
        spark.sql(stmt)
        print(f"OK:     {stmt[:90]}")
    except Exception as e:
        print(f"FAILED: {stmt[:90]}")
        print(f"        -> {type(e).__name__}: {str(e)[:160]}")

# COMMAND ----------

# MAGIC %md
# MAGIC The Builder App is now wired to your data. (The warehouse `CAN_USE` permission was handled in Section 2 when you added the warehouse as an app resource — no separate UI step needed here.)
# MAGIC
# MAGIC ---

# COMMAND ----------

# MAGIC %md
# MAGIC ## Section 4 — Smoke test (recommended)
# MAGIC
# MAGIC Confirm the Builder App can reach your data:
# MAGIC
# MAGIC 1. Open the Builder App URL.
# MAGIC 2. In the chat, paste a prompt like:
# MAGIC
# MAGIC ```
# MAGIC Connect to the SQL warehouse "<your-warehouse-name>" and query the catalog "<your-catalog>", schema "<your-schema>".
# MAGIC How many open care gaps are there by measure? Return a sorted list with counts.
# MAGIC ```
# MAGIC
# MAGIC Replace the placeholders with the values you set in the widgets at the top.
# MAGIC
# MAGIC **Expected:** counts grouped by measure (BCS, COL, CDC-A1C, DEE, FluVax, CBP). If you get that, permissions are wired correctly and you're ready for the workshop.
# MAGIC
# MAGIC **If you see a permission-denied error:** re-check the GRANT output in Section 3 (any FAILED lines need an admin to re-run), and double-check the warehouse Permissions UI step.
